defaultPortal: JCR
portals:
  - name: JCR
    portalId: 23585492
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          CNbjiNiAMRILAA0AAAAA4A0DQAIY1MWfCyDejZwXKO7pDDIUh8jyCiULWJAlVP9ya-4vWd8HRa46NwAABEEAAAB4AAAAAAAAAAAAAAAAAAAABAAAwAcA_v8xPAAABgBEAGAAAAAAAAAAAAAAAAAAMAJCFJJ7tqEEAEqhv4vKSZKdX9ebDptCSgNuYTFSAFoA
        expiresAt: '2023-05-11T13:31:13.260Z'
    personalAccessKey: >-
      CiQ0MjM0MDJlYi1jMmQwLTQ5ZTktOTVmYy1kZDgyM2QyNzg4ZGUQ1MWfCxjejZwXKhkABeaRgmNnjfD2pbpV_BjGZUh9CUq4IMX4SgNuYTE
    sandboxAccountType: null
    parentAccountId: null
