defaultPortal: JCR
portals:
  - name: JCR
    portalId: HUBSPOT_PORTAL_ID
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
         HUBSPOT_CLIENT_ID
        expiresAt: '2023-05-16T12:13:40.569Z'
    personalAccessKey: >-
      HUBSPOT_PERSONAL_ACCESS_KEY
    sandboxAccountType: null
    parentAccountId: null
